[[docs]]
  name = "Prologue"
  weight = 10
  identifier = "prologue"
  url = "/docs/prologue/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

[[main]]
  name = "Documentation"
  url = "/docs/prologue/introduction/"
# url = "/docs/1.0/prologue/introduction/"
  weight = 10

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[[main]]
  name = "Pricing"
  url = "/pricing/"
  weight = 30

[[main]]
  name = "Contact Us"
  url = "/contact/"
  weight = 40

[[social]]
  identifier = "facebook"
  name = "facebook-f" 
  url = "#"

[[social]]
  identifier = "twitter"
  name = "twitter" 
  url = "#"

[[social]]
  identifier = "linkedin"
  name = "linkedin-in" 
  url = "#"

# footer menu left
[[footerleft]]
  name = "About Us"
  url = "#"

[[footerleft]]
  name = "Quick Start"
  url = "#"

[[footerleft]]
  name = "Pricing"
  url = "pricing"

[[footerleft]]
  name = "Blog"
  url = "blog"

[[footerleft]]
  name = "FAQ"
  url = "faq"

[[footerleft]]
  name = "Contact"
  url = "contact"

# footer menu middle
[[footermiddle]]
  name = "Pricing"
  url = "pricing"

[[footermiddle]]
  name = "Platform"
  url = "#"

[[footermiddle]]
  name = "Features"
  url = "#"

# footer menu right
[[footerright]]
  name = "Privacy Policy"
  url = "privacy-policy"

[[footerright]]
  name = "Terms & Conditions"
  url = "terms-conditions"

[[footerright]]
  name = "FAQ"
  url = "faq"