name: github pages

on:
  push:
    branches:
      - gh-pages  # Set a branch to deploy
jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: 
      name: staging
      url: https://beta.qiosqi.com
